name: Update Dependency Graph
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4.1.2
      - uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 17
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v3.1.0
        env:
          GIT_HUB_PACKAGES_ACTOR: ${{ secrets.GIT_HUB_PACKAGES_ACTOR }}
          GIT_HUB_PACKAGES_TOKEN: ${{ secrets.GIT_HUB_PACKAGES_TOKEN }}
